#!/usr/bin/env bash

if
  [[ -s "/home/kbennett/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/environment" ]]
then
  source "/home/kbennett/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/kbennett/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0/environment'" >&2
  exit 1
fi
